export interface ServiceItem {
  id: string;
  title: string;
  slug: string;
  description: string;
  benefit: string;
  tierInclusion?: string;
  category: "Design & UX" | "Engineering & 3D" | "Growth & Infrastructure";
  iconName: string;
}

export const SERVICES: ServiceItem[] = [
  {
    id: "website-design",
    title: "Website Design",
    slug: "website-design",
    category: "Design & UX",
    description: "Editorial, conversion-focused wireframes, tactile visual systems, and bespoke layout design tailored to your brand's unique ethos.",
    benefit: "Commands instant authority, establishes distinct character, and elevates brand perception far above cookie-cutter templates.",
    tierInclusion: "Included in PKG 02–08 & available Standalone",
    iconName: "Layout",
  },
  {
    id: "website-development",
    title: "Website Development",
    slug: "website-development",
    category: "Engineering & 3D",
    description: "Production-grade Next.js App Router architecture, TypeScript rigor, semantic HTML5, and clean CSS token systems.",
    benefit: "Delivers sub-second load times, flawless responsiveness across all viewports, and rock-solid maintainability.",
    tierInclusion: "Core foundation of PKG 01–08 & available Standalone",
    iconName: "Code2",
  },
  {
    id: "ui-ux-design",
    title: "UI/UX Design",
    slug: "ui-ux-design",
    category: "Design & UX",
    description: "User journey mapping, intuitive component hierarchies, tactile interaction physics, and comprehensive design tokens.",
    benefit: "Eliminates user friction, optimizes task completion speeds, and creates delight at every interaction touchpoint.",
    tierInclusion: "Included in PKG 04–08 & available Standalone",
    iconName: "Palette",
  },
  {
    id: "landing-pages",
    title: "Landing Pages",
    slug: "landing-pages",
    category: "Design & UX",
    description: "High-impact, single-goal promotional pages engineered for product launches, campaign funnels, and investor showcases.",
    benefit: "Drives maximum conversion rates with focused messaging hierarchy and zero visual clutter.",
    tierInclusion: "Featured in PKG 01, 04, 05 & available Standalone",
    iconName: "Flame",
  },
  {
    id: "portfolio-websites",
    title: "Portfolio Websites",
    slug: "portfolio-websites",
    category: "Design & UX",
    description: "Immersive case study layouts, interactive lightboxes, and kinetic typography for creative studios, architects, and leaders.",
    benefit: "Presents work with editorial prestige, demonstrating high craftsmanship to prospective clients.",
    tierInclusion: "Included in PKG 03, 04 & available Standalone",
    iconName: "Briefcase",
  },
  {
    id: "ecommerce",
    title: "E-Commerce",
    slug: "ecommerce",
    category: "Engineering & 3D",
    description: "Bespoke product showcases, fluid cart flows, payment gateway integrations, and streamlined customer account portals.",
    benefit: "Accelerates checkout completion and boosts average order value with frictionless, branded purchasing experiences.",
    tierInclusion: "Featured in PKG 06, 08 & available Standalone",
    iconName: "ShoppingBag",
  },
  {
    id: "saas-web-apps",
    title: "SaaS & Web Apps",
    slug: "saas-web-apps",
    category: "Engineering & 3D",
    description: "Multi-tenant web applications, complex dashboard matrices, real-time state management, and authenticated workflows.",
    benefit: "Empowers complex product mechanics with rapid reactivity and clean architectural separation.",
    tierInclusion: "Included in PKG 06, 07, 08 & available Standalone",
    iconName: "Layers",
  },
  {
    id: "3d-websites",
    title: "3D Websites",
    slug: "3d-websites",
    category: "Engineering & 3D",
    description: "Spatial 3D scenes, device models, kinetic wireframes, and shader choreography built using React Three Fiber and Three.js.",
    benefit: "Creates unforgettable spatial immersion that sets a category-defining standard in your industry.",
    tierInclusion: "Featured in PKG 07, 08 & available Standalone",
    iconName: "Box",
  },
  {
    id: "ai-integration",
    title: "AI Integration",
    slug: "ai-integration",
    category: "Engineering & 3D",
    description: "Embedding custom LLM pipelines, semantic vector search, generative media tools, and intelligent conversational agents.",
    benefit: "Automates repetitive user actions and delivers hyper-personalized experiences that enhance product value.",
    tierInclusion: "Available as Custom Commission & in PKG 07–08",
    iconName: "Cpu",
  },
  {
    id: "automation",
    title: "Automation",
    slug: "automation",
    category: "Growth & Infrastructure",
    description: "Event-driven webhook pipelines, CRM sync, automated email routing via Resend, and custom operational triggers.",
    benefit: "Eliminates manual admin bottlenecks and ensures instant response times for incoming client inquiries.",
    tierInclusion: "Included in PKG 06, 08 & available Standalone",
    iconName: "Zap",
  },
  {
    id: "seo",
    title: "SEO Optimization",
    slug: "seo",
    category: "Growth & Infrastructure",
    description: "Semantic JSON-LD schemas, OpenGraph protocol, dynamic sitemaps, heading hierarchy audits, and Core Web Vitals tuning.",
    benefit: "Secures organic search prominence and delivers fast indexing on major search engines.",
    tierInclusion: "Basic in PKG 01–03, Advanced in PKG 04–08 & Standalone",
    iconName: "Search",
  },
  {
    id: "branding",
    title: "Branding Systems",
    slug: "branding",
    category: "Design & UX",
    description: "Comprehensive typographic scales, custom color tokens, logomark guidance, and cohesive digital design guidelines.",
    benefit: "Ensures visual unity and prestige across all present and future digital touchpoints.",
    tierInclusion: "Featured in PKG 05–08 & available Standalone",
    iconName: "Sparkles",
  },
  {
    id: "maintenance",
    title: "Maintenance & Evolution",
    slug: "maintenance",
    category: "Growth & Infrastructure",
    description: "Proactive security patching, performance benchmarks, dependency maintenance, and continuous optimization sprints.",
    benefit: "Guarantees zero downtime, bulletproof security, and ongoing technical evolution post-launch.",
    tierInclusion: "1 Month included in PKG 08 & available on Retainer",
    iconName: "ShieldCheck",
  },
  {
    id: "hosting",
    title: "Edge Hosting & Infrastructure",
    slug: "hosting",
    category: "Growth & Infrastructure",
    description: "Global edge CDN deployment configuration, automated CI/CD pipelines, SSL encryption, and custom domain setup.",
    benefit: "Delivers enterprise-grade 99.99% uptime with global edge caching for instantaneous global responses.",
    tierInclusion: "Configured across all packages & available Standalone",
    iconName: "Globe",
  },
];
